<?php
/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/Resources/Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */

$dictionary['sf_WebActivityDetail'] = [
    'table' => 'sf_webactivitydetail',
    'audited' => true,
    'duplicate_merge' => true,
    'color' => 'ocean',
    'icon' => 'sicon-web-activity-detail-xl',
    'fields' => [
        'webinteractionid' => [
            'required' => false,
            'name' => 'webinteractionid',
            'vname' => 'LBL_WEBINTERACTIONID',
            'type' => 'varchar',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => '100',
            'size' => '20',
        ],
        'websessionid' => [
            'required' => false,
            'name' => 'websessionid',
            'vname' => 'LBL_WEBSESSIONID',
            'type' => 'varchar',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => '100',
            'size' => '20',
        ],
        'interactiondate' => [
            'required' => false,
            'name' => 'interactiondate',
            'vname' => 'LBL_INTERACTIONDATE',
            'type' => 'datetimecombo',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'size' => '20',
            'enable_range_search' => false,
            'dbType' => 'datetime',
        ],
        'protocol' => [
            'required' => false,
            'name' => 'protocol',
            'vname' => 'LBL_PROTOCOL',
            'type' => 'varchar',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => '250',
            'size' => '20',
        ],
        'hostname' => [
            'required' => false,
            'name' => 'hostname',
            'vname' => 'LBL_HOSTNAME',
            'type' => 'varchar',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => '250',
            'size' => '20',
        ],
        'path' => [
            'required' => false,
            'name' => 'path',
            'vname' => 'LBL_PATH',
            'type' => 'varchar',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => '250',
            'size' => '20',
        ],
        'title' => [
            'required' => false,
            'name' => 'title',
            'vname' => 'LBL_TITLE',
            'type' => 'varchar',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => '250',
            'size' => '20',
        ],
        'referrer' => [
            'required' => false,
            'name' => 'referrer',
            'vname' => 'LBL_REFERRER',
            'type' => 'text',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'size' => '20',
            'studio' => 'visible',
            'rows' => '6',
            'cols' => '40',
        ],
        'parameters' => [
            'required' => false,
            'name' => 'parameters',
            'vname' => 'LBL_PARAMETERS',
            'type' => 'varchar',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => '250',
            'size' => '20',
        ],
        'entrypage' => [
            'required' => false,
            'name' => 'entrypage',
            'vname' => 'LBL_ENTRYPAGE',
            'type' => 'varchar',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => '1',
            'size' => '20',
        ],
        'exitpage' => [
            'required' => false,
            'name' => 'exitpage',
            'vname' => 'LBL_EXITPAGE',
            'type' => 'varchar',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => '1',
            'size' => '20',
        ],
        'duration' => [
            'required' => false,
            'name' => 'duration',
            'vname' => 'LBL_DURATION',
            'type' => 'float',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => '8',
            'size' => '20',
            'enable_range_search' => false,
            'precision' => '2',
        ],
        'webactivitydetailid' => [
            'required' => false,
            'name' => 'webactivitydetailid',
            'vname' => 'LBL_WEBACTIVITYDETAILID',
            'type' => 'int',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'size' => '20',
            'enable_range_search' => false,
            'disable_num_format' => '1',
        ],
        'name' => [
            'name' => 'name',
            'vname' => 'LBL_NAME',
            'type' => 'name',
            'link' => true,
            'dbType' => 'varchar',
            'len' => '255',
            'unified_search' => false,
            'full_text_search' => ['boost' => 3],
            'required' => true,
            'importable' => 'false',
            'duplicate_merge' => 'disabled',
            'merge_filter' => 'disabled',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'duplicate_merge_dom_value' => 0,
            'audited' => false,
            'reportable' => true,
            'calculated' => 'true',
            'formula' => '$title',
            'enforced' => true,
            'size' => '20',
        ],
        'sf_webactivitydetail_sf_webactivity' => [
            'name' => 'sf_webactivitydetail_sf_webactivity',
            'type' => 'link',
            'relationship' => 'sf_webactivitydetail_sf_webactivity',
            'source' => 'non-db',
            'vname' => 'LBL_SF_WEBACTIVITYDETAIL_SF_WEBACTIVITY_FROM_SF_WEBACTIVITY_TITLE',
            'id_name' => 'sf_webactivitydetail_sf_webactivitysf_webactivity_ida',
        ],
        'sf_webactivitydetail_sf_webactivity_name' => [
            'name' => 'sf_webactivitydetail_sf_webactivity_name',
            'type' => 'relate',
            'source' => 'non-db',
            'vname' => 'LBL_SF_WEBACTIVITYDETAIL_SF_WEBACTIVITY_FROM_SF_WEBACTIVITY_TITLE',
            'save' => true,
            'id_name' => 'sf_webactivitydetail_sf_webactivitysf_webactivity_ida',
            'link' => 'sf_webactivitydetail_sf_webactivity',
            'table' => 'sf_webactivity',
            'module' => 'sf_webActivity',
            'rname' => 'name',
        ],
        'sf_webactivitydetail_sf_webactivitysf_webactivity_ida' => [
            'name' => 'sf_webactivitydetail_sf_webactivitysf_webactivity_ida',
            'type' => 'id',
            'relationship' => 'sf_webactivitydetail_sf_webactivity',
            'source' => 'non-db',
            'reportable' => false,
            'side' => 'right',
            'vname' => 'LBL_SF_WEBACTIVITYDETAIL_SF_WEBACTIVITY_FROM_SF_WEBACTIVITYDETAIL_TITLE',
        ],
    ],
    'relationships' => [],
    'optimistic_locking' => true,
    'unified_search' => true,
];

VardefManager::createVardef('sf_WebActivityDetail', 'sf_WebActivityDetail', ['basic', 'assignable']);
