<?php
/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/Resources/Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */

$dictionary['sf_Dialog'] = [
    'table' => 'sf_dialogs',
    'audited' => true,
    'duplicate_merge' => true,
    'color' => 'yellow',
    'icon' => 'sicon-landing-pages-xl',
    'fields' => [
        'completed_date' => [
            'required' => false,
            'name' => 'completed_date',
            'vname' => 'LBL_COMPLETED_DATE',
            'type' => 'datetimecombo',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'size' => '20',
            'enable_range_search' => false,
            'dbType' => 'datetime',
        ],
        'dialog_id' => [
            'required' => false,
            'name' => 'dialog_id',
            'vname' => 'LBL_DIALOG_ID',
            'type' => 'int',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'size' => '20',
            'enable_range_search' => false,
            'disable_num_format' => '',
        ],
        'name' => [
            'name' => 'name',
            'vname' => 'LBL_NAME',
            'type' => 'name',
            'link' => true,
            'dbType' => 'varchar',
            'len' => '255',
            'unified_search' => false,
            'full_text_search' => ['boost' => 3],
            'required' => true,
            'importable' => 'required',
            'duplicate_merge' => 'enabled',
            'merge_filter' => 'selected',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'duplicate_merge_dom_value' => '3',
            'audited' => false,
            'reportable' => true,
            'calculated' => false,
            'size' => '20',
        ],
        'dialog_response' => [
            'required' => false,
            'name' => 'dialog_response',
            'vname' => 'LBL_DIALOG_RESPONSE',
            'type' => 'text',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'size' => '20',
            'studio' => 'visible',
            'rows' => '8',
            'cols' => '60',
        ],
        'start_form_id' => [
            'required' => false,
            'name' => 'start_form_id',
            'vname' => 'LBL_START_FORM_ID',
            'type' => 'int',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'size' => '20',
            'enable_range_search' => false,
            'disable_num_format' => '',
        ],
        'sf_dialogs_contacts' => [
            'name' => 'sf_dialogs_contacts',
            'type' => 'link',
            'relationship' => 'sf_dialogs_contacts',
            'source' => 'non-db',
            'vname' => 'LBL_SF_DIALOGS_CONTACTS_FROM_CONTACTS_TITLE',
            'id_name' => 'sf_dialogs_contactscontacts_ida',
        ],
        'sf_dialogs_contacts_name' => [
            'name' => 'sf_dialogs_contacts_name',
            'type' => 'relate',
            'source' => 'non-db',
            'vname' => 'LBL_SF_DIALOGS_CONTACTS_FROM_CONTACTS_TITLE',
            'save' => true,
            'id_name' => 'sf_dialogs_contactscontacts_ida',
            'link' => 'sf_dialogs_contacts',
            'table' => 'contacts',
            'module' => 'Contacts',
            'rname' => 'name',
            'db_concat_fields' => [
                'first_name',
                'last_name',
            ],
        ],
        'sf_dialogs_contactscontacts_ida' => [
            'name' => 'sf_dialogs_contactscontacts_ida',
            'type' => 'id',
            'relationship' => 'sf_dialogs_contacts',
            'source' => 'non-db',
            'reportable' => false,
            'side' => 'right',
            'vname' => 'LBL_SF_DIALOGS_CONTACTS_FROM_SF_DIALOGS_TITLE',
        ],
        'sf_dialogs_leads' => [
            'name' => 'sf_dialogs_leads',
            'type' => 'link',
            'relationship' => 'sf_dialogs_leads',
            'source' => 'non-db',
            'vname' => 'LBL_SF_DIALOGS_LEADS_FROM_LEADS_TITLE',
            'id_name' => 'sf_dialogs_leadsleads_ida',
        ],
        'sf_dialogs_leads_name' => [
            'name' => 'sf_dialogs_leads_name',
            'type' => 'relate',
            'source' => 'non-db',
            'vname' => 'LBL_SF_DIALOGS_LEADS_FROM_LEADS_TITLE',
            'save' => true,
            'id_name' => 'sf_dialogs_leadsleads_ida',
            'link' => 'sf_dialogs_leads',
            'table' => 'leads',
            'module' => 'Leads',
            'rname' => 'name',
            'db_concat_fields' => [
                'first_name',
                'last_name',
            ],
        ],
        'sf_dialogs_leadsleads_ida' => [
            'name' => 'sf_dialogs_leadsleads_ida',
            'type' => 'id',
            'relationship' => 'sf_dialogs_leads',
            'source' => 'non-db',
            'reportable' => false,
            'side' => 'right',
            'vname' => 'LBL_SF_DIALOGS_LEADS_FROM_SF_DIALOGS_TITLE',
        ],
    ],
    'relationships' => [],
    'optimistic_locking' => true,
    'unified_search' => true,
];

VardefManager::createVardef('sf_Dialogs', 'sf_Dialog', ['basic', 'assignable']);
