<?php
/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/Resources/Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */

$dictionary['sf_EventManagement'] = [
    'table' => 'sf_eventmanagement',
    'audited' => true,
    'duplicate_merge' => true,
    'color' => 'teal',
    'icon' => 'sicon-event-mgmt-xl',
    'fields' => [
        'attended' => [
            'required' => false,
            'name' => 'attended',
            'vname' => 'LBL_ATTENDED',
            'type' => 'bool',
            'massupdate' => 0,
            'default' => '0',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => 1,
            'size' => '20',
        ],
        'duration' => [
            'required' => false,
            'name' => 'duration',
            'vname' => 'LBL_DURATION',
            'type' => 'int',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'size' => '20',
            'enable_range_search' => false,
            'disable_num_format' => '',
        ],
        'event_date' => [
            'required' => false,
            'name' => 'event_date',
            'vname' => 'LBL_EVENT_DATE',
            'type' => 'datetimecombo',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'size' => '20',
            'enable_range_search' => false,
            'dbType' => 'datetime',
        ],
        'event_location' => [
            'required' => false,
            'name' => 'event_location',
            'vname' => 'LBL_EVENT_LOCATION',
            'type' => 'varchar',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => '255',
            'size' => '20',
        ],
        'name' => [
            'name' => 'name',
            'vname' => 'LBL_NAME',
            'type' => 'name',
            'link' => true,
            'dbType' => 'varchar',
            'len' => '255',
            'unified_search' => false,
            'full_text_search' => ['boost' => 3],
            'required' => true,
            'importable' => 'required',
            'duplicate_merge' => 'enabled',
            'merge_filter' => 'selected',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'duplicate_merge_dom_value' => '3',
            'audited' => false,
            'reportable' => true,
            'calculated' => false,
            'size' => '20',
        ],
        'lead_source' => [
            'required' => false,
            'name' => 'lead_source',
            'vname' => 'LBL_LEAD_SOURCE',
            'type' => 'varchar',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => '255',
            'size' => '20',
        ],
        'registered' => [
            'required' => false,
            'name' => 'registered',
            'vname' => 'LBL_REGISTERED',
            'type' => 'bool',
            'massupdate' => 0,
            'default' => '0',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => 1,
            'size' => '20',
        ],
        'sf_eventmanagement_contacts' => [
            'name' => 'sf_eventmanagement_contacts',
            'type' => 'link',
            'relationship' => 'sf_eventmanagement_contacts',
            'source' => 'non-db',
            'vname' => 'LBL_SF_EVENTMANAGEMENT_CONTACTS_FROM_CONTACTS_TITLE',
            'id_name' => 'sf_eventmanagement_contactscontacts_ida',
        ],
        'sf_eventmanagement_contacts_name' => [
            'name' => 'sf_eventmanagement_contacts_name',
            'type' => 'relate',
            'source' => 'non-db',
            'vname' => 'LBL_SF_EVENTMANAGEMENT_CONTACTS_FROM_CONTACTS_TITLE',
            'save' => true,
            'id_name' => 'sf_eventmanagement_contactscontacts_ida',
            'link' => 'sf_eventmanagement_contacts',
            'table' => 'contacts',
            'module' => 'Contacts',
            'rname' => 'name',
            'db_concat_fields' => [
                'first_name',
                'last_name',
            ],
        ],
        'sf_eventmanagement_contactscontacts_ida' => [
            'name' => 'sf_eventmanagement_contactscontacts_ida',
            'type' => 'id',
            'relationship' => 'sf_eventmanagement_contacts',
            'source' => 'non-db',
            'reportable' => false,
            'side' => 'right',
            'vname' => 'LBL_SF_EVENTMANAGEMENT_CONTACTS_FROM_SF_EVENTMANAGEMENT_TITLE',
        ],
        'sf_eventmanagement_leads' => [
            'name' => 'sf_eventmanagement_leads',
            'type' => 'link',
            'relationship' => 'sf_eventmanagement_leads',
            'source' => 'non-db',
            'vname' => 'LBL_SF_EVENTMANAGEMENT_LEADS_FROM_LEADS_TITLE',
            'id_name' => 'sf_eventmanagement_leadsleads_ida',
        ],
        'sf_eventmanagement_leads_name' => [
            'name' => 'sf_eventmanagement_leads_name',
            'type' => 'relate',
            'source' => 'non-db',
            'vname' => 'LBL_SF_EVENTMANAGEMENT_LEADS_FROM_LEADS_TITLE',
            'save' => true,
            'id_name' => 'sf_eventmanagement_leadsleads_ida',
            'link' => 'sf_eventmanagement_leads',
            'table' => 'leads',
            'module' => 'Leads',
            'rname' => 'name',
            'db_concat_fields' => [
                'first_name',
                'last_name',
            ],
        ],
        'sf_eventmanagement_leadsleads_ida' => [
            'name' => 'sf_eventmanagement_leadsleads_ida',
            'type' => 'id',
            'relationship' => 'sf_eventmanagement_leads',
            'source' => 'non-db',
            'reportable' => false,
            'side' => 'right',
            'vname' => 'LBL_SF_EVENTMANAGEMENT_LEADS_FROM_SF_EVENTMANAGEMENT_TITLE',
        ],
    ],
    'relationships' => [],
    'optimistic_locking' => true,
    'unified_search' => true,
];

VardefManager::createVardef('sf_EventManagement', 'sf_EventManagement', ['basic', 'assignable']);
