<?php
/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/Resources/Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */

$dictionary['ACLRole'] = [
    'table' => 'acl_roles',
    'color' => 'teal',
    'icon' => 'sicon-role-mgmt-lg',
    'archive' => false,
    'comment' => 'ACL Role definition',
    'fields' => [
        'id' => [
            'name' => 'id',
            'vname' => 'LBL_ID',
            'required' => true,
            'type' => 'id',
            'reportable' => false,
            'comment' => 'Unique identifier',
        ],
        'date_entered' => [
            'name' => 'date_entered',
            'vname' => 'LBL_DATE_ENTERED',
            'type' => 'datetime',
            'required' => true,
            'comment' => 'Date record created',
        ],
        'date_modified' => [
            'name' => 'date_modified',
            'vname' => 'LBL_DATE_MODIFIED',
            'type' => 'datetime',
            'required' => true,
            'comment' => 'Date record last modified',
        ],
        'modified_user_id' => [
            'name' => 'modified_user_id',
            'rname' => 'user_name',
            'id_name' => 'modified_user_id',
            'vname' => 'LBL_MODIFIED',
            'type' => 'assigned_user_name',
            'table' => 'modified_user_id_users',
            'isnull' => 'false',
            'dbType' => 'id',
            'required' => false,
            'len' => 36,
            'reportable' => true,
            'comment' => 'User who last modified record',
        ],
        'created_by' => [
            'name' => 'created_by',
            'rname' => 'user_name',
            'id_name' => 'created_by',
            'vname' => 'LBL_CREATED',
            'type' => 'assigned_user_name',
            'table' => 'created_by_users',
            'isnull' => 'false',
            'dbType' => 'id',
            'len' => 36,
            'comment' => 'User who created record',
        ],
        'name' => [
            'name' => 'name',
            'type' => 'varchar',
            'vname' => 'LBL_NAME',
            'len' => 150,
            'comment' => 'The role name',
        ],
        'description' => [
            'name' => 'description',
            'vname' => 'LBL_DESCRIPTION',
            'type' => 'text',
            'comment' => 'The role description',
        ],
        'deleted' => [
            'name' => 'deleted',
            'vname' => 'LBL_DELETED',
            'type' => 'bool',
            'reportable' => false,
            'comment' => 'Record deletion indicator',
        ],
        'users' => [
            'name' => 'users',
            'type' => 'link',
            'relationship' => 'acl_roles_users',
            'link_class' => 'UserLink',
            'source' => 'non-db',
            'vname' => 'LBL_USERS',
        ],
        'actions' => [
            'name' => 'actions',
            'type' => 'link',
            'relationship' => 'acl_roles_actions',
            'source' => 'non-db',
            'module' => 'ACLActions',
            'bean_name' => 'ACLAction',
            'rel_fields' => [
                'access_override' => [
                    'type' => 'int',
                ],
            ],
        ],
        'access_override' => [
            'name' => 'access_override',
            'type' => 'int',
            'studio' => 'false',
            'source' => 'non-db',
            'massupdate' => false,
            'link' => 'actions',
            'rname_link' => 'access_override',
            'link_type' => 'one',
        ],
        'acl_role_sets' => [
            'name' => 'acl_role_sets',
            'type' => 'link',
            'source' => 'non-db',
            'relationship' => 'acl_role_sets_acl_roles',
        ],
    ],
    'acls' => ['SugarACLDeveloperOrAdmin' => ['aclModule' => 'Users']],
    'indices' => [
        ['name' => 'aclrolespk', 'type' => 'primary', 'fields' => ['id']],
        ['name' => 'idx_aclrole_id_del', 'type' => 'index', 'fields' => ['id', 'deleted']],
        ['name' => 'idx_aclrole_name', 'type' => 'index', 'fields' => ['name']],
    ],
];

$dictionary['ACLRoleSet'] = [
    'table' => 'acl_role_sets',
    'archive' => false,
    'fields' => [
        'id' => [
            'name' => 'id',
            'vname' => 'LBL_ID',
            'type' => 'id',
            'required' => true,
            'reportable' => true,
            'duplicate_on_record_copy' => 'no',
            'comment' => 'Unique identifier',
            'mandatory_fetch' => true,
        ],
        'name' => [
            'name' => 'name',
            'vname' => 'LBL_NAME',
            'type' => 'name',
            'dbType' => 'varchar',
            'len' => 255,
            'unified_search' => true,
            'full_text_search' => [
                'enabled' => true,
                'searchable' => true,
                'boost' => 1.55,
            ],
            'required' => true,
            'importable' => 'required',
            'duplicate_merge' => 'enabled',
            'merge_filter' => 'selected',
            'duplicate_on_record_copy' => 'always',
        ],
        'date_entered' => [
            'name' => 'date_entered',
            'vname' => 'LBL_DATE_ENTERED',
            'type' => 'datetime',
            'group' => 'created_by_name',
            'comment' => 'Date record created',
            'enable_range_search' => true,
            'options' => 'date_range_search_dom',
            'studio' => [
                'portaleditview' => false,
            ],
            'duplicate_on_record_copy' => 'no',
            'readonly' => true,
            'massupdate' => false,
            'full_text_search' => [
                'enabled' => true,
                'searchable' => false,
            ],
        ],
        'date_modified' => [
            'name' => 'date_modified',
            'vname' => 'LBL_DATE_MODIFIED',
            'type' => 'datetime',
            'group' => 'modified_by_name',
            'comment' => 'Date record last modified',
            'enable_range_search' => true,
            'full_text_search' => [
                'enabled' => true,
                'searchable' => false,
                'sortable' => true,
            ],
            'studio' => [
                'portaleditview' => false,
            ],
            'options' => 'date_range_search_dom',
            'duplicate_on_record_copy' => 'no',
            'readonly' => true,
            'massupdate' => false,
        ],
        'modified_user_id' => [
            'name' => 'modified_user_id',
            'rname' => 'user_name',
            'id_name' => 'modified_user_id',
            'vname' => 'LBL_MODIFIED',
            'type' => 'assigned_user_name',
            'table' => 'users',
            'isnull' => false,
            'group' => 'modified_by_name',
            'dbType' => 'id',
            'reportable' => true,
            'comment' => 'User who last modified record',
            'massupdate' => false,
            'duplicate_on_record_copy' => 'no',
            'readonly' => true,
            'full_text_search' => [
                'enabled' => true,
                'searchable' => false,
                'type' => 'id',
                'aggregations' => [
                    'modified_user_id' => [
                        'type' => 'MyItems',
                        'label' => 'LBL_AGG_MODIFIED_BY_ME',
                    ],
                ],
            ],
            'processes' => [
                'types' => [
                    'RR' => false,
                    'ALL' => true,
                ],
            ],
        ],
        'modified_by_name' => [
            'name' => 'modified_by_name',
            'vname' => 'LBL_MODIFIED',
            'type' => 'relate',
            'reportable' => false,
            'source' => 'non-db',
            'rname' => 'full_name',
            'table' => 'users',
            'id_name' => 'modified_user_id',
            'module' => 'Users',
            'link' => 'modified_user_link',
            'duplicate_merge' => 'disabled',
            'massupdate' => false,
            'duplicate_on_record_copy' => 'no',
            'readonly' => true,
            'sort_on' => [
                'last_name',
            ],
            'exportable' => true,
        ],
        'created_by' => [
            'name' => 'created_by',
            'rname' => 'user_name',
            'id_name' => 'modified_user_id',
            'vname' => 'LBL_CREATED',
            'type' => 'assigned_user_name',
            'table' => 'users',
            'isnull' => false,
            'dbType' => 'id',
            'group' => 'created_by_name',
            'comment' => 'User who created record',
            'massupdate' => false,
            'duplicate_on_record_copy' => 'no',
            'readonly' => true,
            'full_text_search' => [
                'enabled' => true,
                'searchable' => false,
                'type' => 'id',
                'aggregations' => [
                    'created_by' => [
                        'type' => 'MyItems',
                        'label' => 'LBL_AGG_CREATED_BY_ME',
                    ],
                ],
            ],
            'processes' => [
                'types' => [
                    'RR' => false,
                    'ALL' => true,
                ],
            ],
        ],
        'created_by_name' => [
            'name' => 'created_by_name',
            'vname' => 'LBL_CREATED',
            'type' => 'relate',
            'reportable' => false,
            'link' => 'created_by_link',
            'rname' => 'full_name',
            'source' => 'non-db',
            'table' => 'users',
            'id_name' => 'created_by',
            'module' => 'Users',
            'duplicate_merge' => 'disabled',
            'massupdate' => false,
            'duplicate_on_record_copy' => 'no',
            'readonly' => true,
            'sort_on' => [
                'last_name',
            ],
            'exportable' => true,
        ],
        'description' => [
            'name' => 'description',
            'vname' => 'LBL_DESCRIPTION',
            'type' => 'text',
            'comment' => 'Full text of the note',
            'full_text_search' => [
                'enabled' => true,
                'searchable' => true,
                'boost' => 0.5,
            ],
            'rows' => 6,
            'cols' => 80,
            'duplicate_on_record_copy' => 'always',
        ],
        'deleted' => [
            'name' => 'deleted',
            'vname' => 'LBL_DELETED',
            'type' => 'bool',
            'default' => '0',
            'reportable' => false,
            'duplicate_on_record_copy' => 'no',
            'comment' => 'Record deletion indicator',
        ],
        'created_by_link' => [
            'name' => 'created_by_link',
            'type' => 'link',
            'relationship' => 'aclrolesets_created_by',
            'vname' => 'LBL_CREATED_USER',
            'link_type' => 'one',
            'module' => 'Users',
            'bean_name' => 'User',
            'source' => 'non-db',
            'side' => 'right',
        ],
        'modified_user_link' => [
            'name' => 'modified_user_link',
            'type' => 'link',
            'relationship' => 'aclrolesets_modified_user',
            'vname' => 'LBL_MODIFIED_USER',
            'link_type' => 'one',
            'module' => 'Users',
            'bean_name' => 'User',
            'source' => 'non-db',
            'side' => 'right',
        ],
        'activities' => [
            'name' => 'activities',
            'type' => 'link',
            'relationship' => 'aclroleset_activities',
            'vname' => 'LBL_ACTIVITY_STREAM',
            'link_type' => 'many',
            'module' => 'Activities',
            'bean_name' => 'Activity',
            'source' => 'non-db',
        ],
        'hash' => [
            'name' => 'hash',
            'type' => 'varchar',
            'len' => 32,
            'isnull' => false,
        ],
        'acl_roles' => [
            'name' => 'acl_roles',
            'type' => 'link',
            'source' => 'non-db',
            'relationship' => 'acl_role_sets_acl_roles',
            'duplicate_merge' => 'disabled',
        ],
        'following' => [
            'massupdate' => false,
            'name' => 'following',
            'vname' => 'LBL_FOLLOWING',
            'type' => 'bool',
            'source' => 'non-db',
            'comment' => 'Is user following this record',
            'studio' => 'false',
            'link' => 'following_link',
            'rname' => 'id',
            'rname_exists' => true,
        ],
        'following_link' => [
            'name' => 'following_link',
            'type' => 'link',
            'relationship' => 'aclrolesets_following',
            'source' => 'non-db',
            'vname' => 'LBL_FOLLOWING',
            'reportable' => false,
        ],
        'my_favorite' => [
            'massupdate' => false,
            'name' => 'my_favorite',
            'vname' => 'LBL_FAVORITE',
            'type' => 'bool',
            'source' => 'non-db',
            'comment' => 'Favorite for the user',
            'studio' => [
                'list' => false,
                'recordview' => false,
                'basic_search' => false,
                'advanced_search' => false,
            ],
            'link' => 'favorite_link',
            'rname' => 'id',
            'rname_exists' => true,
        ],
        'favorite_link' => [
            'name' => 'favorite_link',
            'type' => 'link',
            'relationship' => 'aclrolesets_favorite',
            'source' => 'non-db',
            'vname' => 'LBL_FAVORITE',
            'reportable' => false,
            'workflow' => false,
            'full_text_search' => [
                'type' => 'favorites',
                'enabled' => true,
                'searchable' => false,
                'aggregations' => [
                    'favorite_link' => [
                        'type' => 'MyItems',
                        'options' => [
                            'field' => 'user_favorites',
                        ],
                    ],
                ],
            ],
        ],
        'tag' => [
            'name' => 'tag',
            'vname' => 'LBL_TAGS',
            'type' => 'tag',
            'link' => 'tag_link',
            'source' => 'non-db',
            'module' => 'Tags',
            'relate_collection' => true,
            'studio' => [
                'portal' => false,
                'base' => [
                    'popuplist' => false,
                    'popupsearch' => false,
                ],
                'mobile' => [
                    'wirelesseditview' => true,
                    'wirelessdetailview' => true,
                ],
            ],
            'massupdate' => true,
            'exportable' => true,
            'sortable' => false,
            'rname' => 'name',
            'full_text_search' => [
                'enabled' => true,
                'searchable' => false,
            ],
        ],
        'tag_link' => [
            'name' => 'tag_link',
            'type' => 'link',
            'vname' => 'LBL_TAGS_LINK',
            'relationship' => 'aclrolesets_tags',
            'source' => 'non-db',
            'exportable' => false,
            'duplicate_merge' => 'disabled',
        ],
        'commentlog' => [
            'name' => 'commentlog',
            'vname' => 'LBL_COMMENTLOG',
            'type' => 'collection',
            'displayParams' => [
                'type' => 'commentlog',
                'fields' => [
                    'entry',
                    'date_entered',
                    'created_by_name',
                ],
                'max_num' => 100,
            ],
            'links' => [
                'commentlog_link',
            ],
            'order_by' => 'date_entered:asc',
            'source' => 'non-db',
            'module' => 'CommentLog',
            'studio' => [
                'listview' => false,
                'recordview' => true,
                'previewview' => true,
                'wirelesseditview' => false,
                'wirelessdetailview' => true,
                'wirelesslistview' => false,
                'wireless_basic_search' => false,
                'wireless_advanced_search' => false,
            ],
            'full_text_search' => [
                'enabled' => true,
                'searchable' => true,
            ],
        ],
        'commentlog_link' => [
            'name' => 'commentlog_link',
            'type' => 'link',
            'vname' => 'LBL_COMMENTLOG_LINK',
            'relationship' => 'aclrolesets_commentlog',
            'source' => 'non-db',
            'exportable' => false,
            'duplicate_merge' => 'disabled',
        ],
        'locked_fields' => [
            'name' => 'locked_fields',
            'vname' => 'LBL_LOCKED_FIELDS',
            'type' => 'locked_fields',
            'link' => 'locked_fields_link',
            'source' => 'non-db',
            'module' => 'pmse_BpmProcessDefinition',
            'relate_collection' => true,
            'studio' => false,
            'massupdate' => false,
            'exportable' => false,
            'sortable' => false,
            'rname' => 'pro_locked_variables',
            'collection_fields' => [
                'pro_locked_variables',
            ],
            'full_text_search' => [
                'enabled' => false,
                'searchable' => false,
            ],
            'hideacl' => true,
        ],
        'locked_fields_link' => [
            'name' => 'locked_fields_link',
            'type' => 'link',
            'vname' => 'LBL_LOCKED_FIELDS_LINK',
            'relationship' => 'aclrolesets_locked_fields',
            'source' => 'non-db',
            'exportable' => false,
            'duplicate_merge' => 'disabled',
        ],
        'sync_key' => [
            'is_sync_key' => true,
            'name' => 'sync_key',
            'vname' => 'LBL_SYNC_KEY',
            'type' => 'varchar',
            'enforced' => '',
            'required' => false,
            'massupdate' => false,
            'readonly' => true,
            'default' => null,
            'isnull' => true,
            'no_default' => false,
            'comments' => 'External default id of the remote integration record',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'merge_filter' => 'disabled',
            'duplicate_on_record_copy' => 'no',
            'audited' => true,
            'reportable' => true,
            'unified_search' => false,
            'calculated' => false,
            'len' => '100',
            'size' => '20',
            'studio' => [
                'recordview' => true,
                'wirelessdetailview' => true,
                'listview' => false,
                'wirelesseditview' => false,
                'wirelesslistview' => false,
                'wireless_basic_search' => false,
                'wireless_advanced_search' => false,
                'portallistview' => false,
                'portalrecordview' => false,
                'portaleditview' => false,
            ],
        ],
    ],
    'indices' => [
        'id' => [
            'name' => 'idx_aclrolesets_pk',
            'type' => 'primary',
            'fields' => [
                'id',
            ],
        ],
        'date_modified' => [
            'name' => 'idx_acl_role_sets_del_d_m',
            'type' => 'index',
            'fields' => [
                'deleted',
                'date_modified',
                'id',
            ],
        ],
        'deleted' => [
            'name' => 'idx_acl_role_sets_id_del',
            'type' => 'index',
            'fields' => [
                'id',
                'deleted',
            ],
        ],
        'date_entered' => [
            'name' => 'idx_acl_role_sets_del_d_e',
            'type' => 'index',
            'fields' => [
                'deleted',
                'date_entered',
                'id',
            ],
        ],
        'name_del' => [
            'name' => 'idx_acl_role_sets_name_del',
            'type' => 'index',
            'fields' => [
                'name',
                'deleted',
            ],
        ],
        'hash' => [
            'name' => 'idx_acl_role_sets_hash',
            'type' => 'unique',
            'fields' => [
                'hash',
            ],
        ],
        'sync_key' => [
            'name' => 'idx_acl_role_sets_skey',
            'type' => 'unique',
            'fields' => [
                'sync_key',
            ],
        ],
    ],
    'relationships' => [
        'aclrolesets_modified_user' => [
            'lhs_module' => 'Users',
            'lhs_table' => 'users',
            'lhs_key' => 'id',
            'rhs_module' => 'ACLRoleSets',
            'rhs_table' => 'acl_role_sets',
            'rhs_key' => 'modified_user_id',
            'relationship_type' => 'one-to-many',
        ],
        'aclrolesets_created_by' => [
            'lhs_module' => 'Users',
            'lhs_table' => 'users',
            'lhs_key' => 'id',
            'rhs_module' => 'ACLRoleSets',
            'rhs_table' => 'acl_role_sets',
            'rhs_key' => 'created_by',
            'relationship_type' => 'one-to-many',
        ],
        'aclroleset_activities' => [
            'lhs_module' => 'ACLRoleSets',
            'lhs_table' => 'acl_role_sets',
            'lhs_key' => 'id',
            'rhs_module' => 'Activities',
            'rhs_table' => 'activities',
            'rhs_key' => 'id',
            'rhs_vname' => 'LBL_ACTIVITY_STREAM',
            'relationship_type' => 'many-to-many',
            'join_table' => 'activities_users',
            'join_key_lhs' => 'parent_id',
            'join_key_rhs' => 'activity_id',
            'relationship_role_column' => 'parent_type',
            'relationship_role_column_value' => 'ACLRoleSets',
        ],
        'aclrolesets_following' => [
            'lhs_module' => 'Users',
            'lhs_table' => 'users',
            'lhs_key' => 'id',
            'rhs_module' => 'ACLRoleSets',
            'rhs_table' => 'acl_role_sets',
            'rhs_key' => 'id',
            'relationship_type' => 'user-based',
            'join_table' => 'subscriptions',
            'join_key_lhs' => 'created_by',
            'join_key_rhs' => 'parent_id',
            'relationship_role_column' => 'parent_type',
            'relationship_role_column_value' => 'ACLRoleSets',
            'user_field' => 'created_by',
        ],
        'aclrolesets_favorite' => [
            'lhs_module' => 'Users',
            'lhs_table' => 'users',
            'lhs_key' => 'id',
            'rhs_module' => 'ACLRoleSets',
            'rhs_table' => 'acl_role_sets',
            'rhs_key' => 'id',
            'relationship_type' => 'user-based',
            'join_table' => 'sugarfavorites',
            'join_key_lhs' => 'modified_user_id',
            'join_key_rhs' => 'record_id',
            'relationship_role_column' => 'module',
            'relationship_role_column_value' => 'ACLRoleSets',
            'user_field' => 'created_by',
        ],
        'aclrolesets_tags' => [
            'lhs_module' => 'ACLRoleSets',
            'lhs_table' => 'acl_role_sets',
            'lhs_key' => 'id',
            'rhs_module' => 'Tags',
            'rhs_table' => 'tags',
            'rhs_key' => 'id',
            'relationship_type' => 'many-to-many',
            'join_table' => 'tag_bean_rel',
            'join_key_lhs' => 'bean_id',
            'join_key_rhs' => 'tag_id',
            'relationship_role_column' => 'bean_module',
            'relationship_role_column_value' => 'ACLRoleSets',
            'dynamic_subpanel' => true,
        ],
        'aclrolesets_commentlog' => [
            'lhs_module' => 'ACLRoleSets',
            'lhs_table' => 'acl_role_sets',
            'lhs_key' => 'id',
            'rhs_module' => 'CommentLog',
            'rhs_table' => 'commentlog',
            'rhs_key' => 'id',
            'relationship_type' => 'many-to-many',
            'join_table' => 'commentlog_rel',
            'join_key_lhs' => 'record_id',
            'join_key_rhs' => 'commentlog_id',
            'relationship_role_column' => 'module',
            'relationship_role_column_value' => 'ACLRoleSets',
        ],
        'aclrolesets_locked_fields' => [
            'lhs_module' => 'ACLRoleSets',
            'lhs_table' => 'acl_role_sets',
            'lhs_key' => 'id',
            'rhs_module' => 'pmse_BpmProcessDefinition',
            'rhs_table' => 'pmse_bpm_process_definition',
            'rhs_key' => 'id',
            'relationship_type' => 'many-to-many',
            'join_table' => 'locked_field_bean_rel',
            'join_key_lhs' => 'bean_id',
            'join_key_rhs' => 'pd_id',
            'relationship_role_column' => 'bean_module',
            'relationship_role_column_value' => 'ACLRoleSets',
        ],
        'aclrolesets_audit' => [
            'lhs_module' => 'ACLRoleSets',
            'lhs_table' => 'acl_role_sets',
            'lhs_key' => 'id',
            'rhs_module' => 'Audit',
            'rhs_table' => 'acl_role_sets_audit',
            'rhs_key' => 'parent_id',
            'relationship_type' => 'one-to-many',
        ],
    ],
    'acls' => [
        'SugarACLLockedFields' => true,
    ],
    'duplicate_check' => [
        'enabled' => true,
        'FilterDuplicateCheck' => [
            'filter_template' => [
                [
                    'name' => [
                        '$starts' => '$name',
                    ],
                ],
            ],
            'ranking_fields' => [
                [
                    'in_field_name' => 'name',
                    'dupe_field_name' => 'name',
                ],
            ],
        ],
    ],
    'favorites' => true,
    'custom_fields' => false,
    'has_pii_fields' => false,
];
